#!/usr/bin/env python3
# SPDX-FileCopyrightText: 2026 Canonical, Ltd.
# SPDX-License-Identifier: GPL-3.0-only
"""Generate tests/e2e/scenarios/matrix.env from vendors.yaml + scenario.yaml files.

Also renders backend.conf.j2 templates to tests/e2e/drivers/<driver_dir>/cinder-backend.conf
by replacing Jinja2 ``{{ VAR }}`` with bash ``${VAR}`` form. The rendered conf files are
committed to the repo; the existing configure_cinder_backend() sed pipeline performs the
final substitution of actual IP/port values at test runtime.

Usage:
    # Regenerate matrix.env and render any j2 templates:
    python scripts/generate_e2e_matrix.py

    # Check mode (used by CI): exit 1 if matrix.env would change:
    python scripts/generate_e2e_matrix.py --check
"""

from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path

import yaml

REPO_ROOT = Path(__file__).resolve().parent.parent
VENDORS_YAML = REPO_ROOT / "tests" / "vendors.yaml"
VENDORS_DIR = REPO_ROOT / "tests" / "e2e" / "vendors"
DRIVERS_DIR = REPO_ROOT / "tests" / "e2e" / "drivers"
MATRIX_FILE = REPO_ROOT / "tests" / "e2e" / "scenarios" / "matrix.env"

_MATRIX_HEADER = """\
#!/usr/bin/env bash
# SPDX-FileCopyrightText: 2026 Canonical, Ltd.
# SPDX-License-Identifier: GPL-3.0-only
#
# Scenario matrix — AUTO-GENERATED by scripts/generate_e2e_matrix.py
# DO NOT EDIT BY HAND.
# To add or change scenarios, edit:
#   tests/vendors.yaml
#   tests/e2e/vendors/<vendor>/<scenario>/scenario.yaml
# Then re-run: python scripts/generate_e2e_matrix.py
#
# Each entry: DRIVER_DIR  MODE  NEEDS_FC

SCENARIOS=(
"""

_MATRIX_FOOTER = ")\n"


def _j2_to_bash(content: str) -> str:
    """Translate Jinja2 ``{{ VAR }}`` to bash ``${VAR}`` form.

    This is a straight token replacement — no Jinja2 runtime is required.
    The resulting conf file is rendered to bash-variable form so that the
    existing configure_cinder_backend() sed pipeline can substitute actual
    values at test runtime.
    """
    return re.sub(r"\{\{\s*(\w+)\s*\}\}", r"${\1}", content)


def load_vendors() -> list[dict]:
    with open(VENDORS_YAML) as fh:
        data = yaml.safe_load(fh)
    return data["vendors"]


def collect_rows(vendors: list[dict]) -> list[tuple[str, str, str]]:
    """Return ordered list of (driver_dir, mode, needs_fc_str) matrix rows.

    Iterates vendors in declaration order. Each scenario.yaml may declare
    a ``modes`` list (e.g. [non-vhost, vhost]) to emit multiple rows per
    scenario, or a single ``mode`` string for one row.
    """
    rows: list[tuple[str, str, str]] = []
    for vendor in vendors:
        if not vendor.get("e2e_required", True):
            continue
        pdir = vendor["personality_dir"]
        for scenario_meta in vendor.get("scenarios", []):
            sname = scenario_meta["name"]
            scenario_yaml = VENDORS_DIR / pdir / sname / "scenario.yaml"
            if not scenario_yaml.exists():
                print(
                    f"WARNING: missing scenario.yaml for {pdir}/{sname} — skipping",
                    file=sys.stderr,
                )
                continue
            with open(scenario_yaml) as fh:
                s = yaml.safe_load(fh)

            driver_dir = s.get("driver_dir", sname)
            needs_fc = str(s.get("needs_fc", False)).lower()

            # Support both `mode: non-vhost` (single) and `modes: [non-vhost, vhost]` (multi)
            if "modes" in s:
                modes = s["modes"]
            elif "mode" in s:
                modes = [s["mode"]]
            else:
                modes = ["non-vhost"]

            for mode in modes:
                rows.append((driver_dir, mode, needs_fc))
    return rows


def render_templates(vendors: list[dict], dry_run: bool = False) -> list[str]:
    """Render backend.conf.j2 → cinder-backend.conf for each scenario that has a template.

    Returns a list of paths written (relative to repo root).
    """
    written: list[str] = []
    for vendor in vendors:
        if not vendor.get("e2e_required", True):
            continue
        pdir = vendor["personality_dir"]
        for scenario_meta in vendor.get("scenarios", []):
            sname = scenario_meta["name"]
            scenario_dir = VENDORS_DIR / pdir / sname
            j2_path = scenario_dir / "backend.conf.j2"
            if not j2_path.exists():
                continue
            scenario_yaml = scenario_dir / "scenario.yaml"
            if not scenario_yaml.exists():
                continue
            with open(scenario_yaml) as fh:
                s = yaml.safe_load(fh)
            driver_dir = s.get("driver_dir", sname)
            out_path = DRIVERS_DIR / driver_dir / "cinder-backend.conf"

            rendered = _j2_to_bash(j2_path.read_text())

            if not dry_run:
                out_path.parent.mkdir(parents=True, exist_ok=True)
                out_path.write_text(rendered)
            written.append(str(out_path.relative_to(REPO_ROOT)))
    return written


def build_matrix_content(rows: list[tuple[str, str, str]]) -> str:
    lines = [_MATRIX_HEADER]
    for driver_dir, mode, needs_fc in rows:
        lines.append(f'  "{driver_dir}  {mode}  {needs_fc}"\n')
    lines.append(_MATRIX_FOOTER)
    return "".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check",
        action="store_true",
        help="Check mode: verify matrix.env matches what would be generated. "
             "Exit 1 if out of date (used by CI to detect hand-edited drift).",
    )
    args = parser.parse_args()

    vendors = load_vendors()
    rows = collect_rows(vendors)
    new_content = build_matrix_content(rows)

    if args.check:
        existing = MATRIX_FILE.read_text() if MATRIX_FILE.exists() else ""
        if existing != new_content:
            print(
                "FAIL: tests/e2e/scenarios/matrix.env is out of date.\n"
                "Run:  python scripts/generate_e2e_matrix.py",
                file=sys.stderr,
            )
            # Show a simple diff hint
            existing_lines = set(existing.splitlines())
            new_lines = set(new_content.splitlines())
            for line in sorted(new_lines - existing_lines):
                if line.strip():
                    print(f"  + {line}", file=sys.stderr)
            for line in sorted(existing_lines - new_lines):
                if line.strip():
                    print(f"  - {line}", file=sys.stderr)
            return 1
        print("OK: tests/e2e/scenarios/matrix.env is up to date.")
        return 0

    # Render j2 templates first
    rendered = render_templates(vendors)
    for path in rendered:
        print(f"Rendered: {path}")

    # Write matrix.env
    MATRIX_FILE.write_text(new_content)
    print(f"Written:  {MATRIX_FILE.relative_to(REPO_ROOT)}")
    print(f"          {len(rows)} scenario row(s) across {len(vendors)} vendor(s).")
    return 0


if __name__ == "__main__":
    sys.exit(main())
